### ISSUE TITLE
Database doesn't work really well

### ISSUE THREAD

**Issue by Varkaria** [NotPeOpLe/tournament-web#5]
I think you database doesn't have enough table or something like "JSON_ARRAYAGG"
can you push about lastest database and working fully for this project please?

**Comment by NotPeOpLe** [comment]
JSON_ARRAYAGG is function in MySQL 5.7.22↑

**Comment by Varkaria** [comment]
ok i get that.
btw do you have about discord?
i think it's will have a faster communicate about this project

**Comment by NotPeOpLe** [comment]
840#8400
